config/routes.rb
Rails.application.routes.draw do

  root 'market#index'

  #resources :sales do
  # resources :items
  #end

  resources :purchases do
    resources :items
  end
  
  post "/purchases/add_item" => "purchases#add_item"
  
  delete "/purchases/:purchase_id/items/:id" => "purchases#delete_item"

  get 'purchases/:id/finished' => 'purchases#finished', as: :finished

  resources :stocks
  
  resources :products

  resources :suppliers

  resources :units

  resources :categories

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :products
  validates :description, presence: true, allow_blank: false, length: {minimum: 3}
  validates :acronym, presence: true, allow_blank: false, length: {minimum: 1}
  validates :description, uniqueness: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:description, :acronym)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<div class="text-center">
    <%= form_for(@unit) do |f| %>
      <% if @unit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

          <ul>
          <% @unit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :description, placeholder: 'Descrição',class: 'form-control sel' %>
      </div>
      <div class="field">
        <%= f.text_field :acronym, placeholder: 'Sigla',class: 'form-control sel' %>
      </div>
      <div class="actions">
        <%= f.submit nil, class: 'btn btn-primary' %><%= link_to t(:back), units_path, class: 'btn btn-default back2' %>
      </div>
    <% end %>
</div>

app/views/units/edit.html.erb
<h2 class="text-center"><%= t(:editing_unit) %></h2>

<%= render 'form' %>

app/views/units/index.html.erb
<h2 class="subhead navbar text-center alert"><%= t(:listing_units) %></h2>

<table class="table">
  <thead>
    <tr>
      <th class="text-center"><%=t(:description)%></th>
      <th class="text-center"><%=t(:acronym)%></th>
      <th colspan="3" class="text-center"><%= t(:action)%></th>
    </tr>
  </thead>

  <tbody class="text-center">
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.description %></td>
        <td><%= unit.acronym %></td>
        <td><%= link_to 'Detalhar', unit, class: 'btn btn-info' %></td>
        <td><%= link_to 'Editar', edit_unit_path(unit), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Excluir', unit, method: :delete, data: { confirm: t(:confirm_destroy) }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(:new_unit), new_unit_path, class: 'btn btn-primary' %>
<%= link_to t(:back), units_path, class: 'btn btn-default back2' %>
<br><br><br>

app/views/units/new.html.erb
<h2 class="text-center"><%= t(:new_unit) %></h2>

<%= render 'form' %>

app/views/units/show.html.erb
<h2 class="subhead navbar text-center alert"><%= t(:details) %></h2>

<div class="scheduler-border">

    <p>
      <strong><%= t(:description)%>:</strong>
      <%= @unit.description %>
    </p>

    <p>
      <strong><%= t(:acronym)%>:</strong>
      <%= @unit.acronym %>
    </p>

</div>

<%= link_to t(:edit), edit_unit_path(@unit), class: 'btn btn-success' %>
<%= link_to t(:back), units_path, class: 'btn btn-default back2' %>
<br><br><br>